### ISSUE TITLE
Missing copyright/license

### ISSUE THREAD

**Issue by djmdjm** [patrickfav/bcrypt#19]
https://github.com/patrickfav/bcrypt/blob/master/modules/bcrypt/src/main/java/at/favre/lib/crypto/bcrypt/BCryptOpenBSDProtocol.java is derived from jBCrypt's src/org/mindrot/jbcrypt/BCrypt.java but you have removed my copyright/license from the start of the file.

Please add the original license text back and also include it in your top-level LICENSE file. You cannot morally or legally remove the copyright or license from code you have not written without agreement from the author.

I notice that Radix64Encoder.java is under a different license too (GPL), but this is not reflected in your top-level LICENSE file either. This is even more problematic, because the GPL is incompatible with your chosen Apache license (see https://www.gnu.org/licenses/license-list.en.html#apache2) and imposes a number of conditions that you and your users should be aware of: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by patrickfav** [comment]
Hi,

You are correct, the license header is missing - this was due to oversight on my part and not done with malice intend (as can be seen in the readme.md where I credit your work). I will fix this issue asap.

Previous versions of this project had code that fell under "GPLv2 with classpath exception" (ie. `Radix64Encoder`). As not an expert on software licenses I did my own investigation which pointed to the same issues you describe in your last paragraph (see this question under [opensource.stackexchange.com](https://opensource.stackexchange.com/questions/7164/i-modified-and-used-gpl2-code-in-my-apache-2-open-source-project-can-my-projec)). This implementation was switched with one under Apache v2 (see #8 ) in v0.5+. There is also a hint in the release notes warning to use this or a newer version (see https://github.com/patrickfav/bcrypt/releases/tag/v0.5.0). To my knowledge there is no code under GPL anymore in this project.

Cheers.

**Comment by patrickfav** [comment]
Ah, I see I left the old license header in there, that was the confusion about GPL.

**Comment by patrickfav** [comment]
The changes in #20 should resolve the license issues. Feel free to update this ticket or open a new one I you find the fix unsatisfactory. Apologies again for not correctly following the requirement of the license and properly credit your work.
