### ISSUE TITLE
(only test scope): bcprov-jdk15on package version 1.60 is vulnerable to CVE-2020-15522

### ISSUE THREAD

**Issue by Abderrahman-byte** [patrickfav/bcrypt#40]
bcprov-jdk15on package must be updated to version 1.70

**Comment by scala-impala** [comment]
@patrickfav Hi there, is this lib still being maintained?

**Comment by patrickfav** [comment]
Hi,

First, thanks for reporting the CVE!

However, this is a non-issue since bcprov-jdk15on is ONLY used in the TEST scope and is not a dependency during runtime.
The test is also just check if the output is compatible with the output of bouncy castle (a regression test so to speak).

![Screenshot 2022-09-11 130047](https://user-images.githubusercontent.com/2980711/189523939-0ac7e034-8698-4723-bdd2-d9c88f6ba362.jpg)


I will soon update all the dependencies, therefore also this dependency (need to migrate away from Jcenter).

**Comment by patrickfav** [comment]
This warning is now fixed with 0.10.0
